DeanOffice/DeanOffice.Application/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace DeanOffice.Application.Controllers
{
    [Route("about")]
    public class AboutController : Controller
    {
        [HttpGet("contact")]
        public IActionResult Contact()
        {
            return View();
        }
    }
}

DeanOffice/DeanOffice.Application/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DeanOffice.Application.Controllers
{
    [Route("admin")]
    [Authorize(Policy = "DeanOfficer")]
    public class AdminController : Controller
    {
        [HttpGet("")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

DeanOffice/DeanOffice.Application/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using AutoMapper;
using DeanOffice.Application.Utils;
using DeanOffice.Identity.Models;
using DeanOffice.Models.DataTransferObjects.Course;
using DeanOffice.Models.Utils;
using DeanOffice.Models.ViewModels.Dashboard;
using DeanOffice.Repository.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DeanOffice.Application.Controllers
{
    [Authorize(Policy = "IsValidUser")]
    [Route("dashboard")]
    public class DashboardController : Controller
    {
        private readonly ICourseRepository _courses;
        private readonly IMapper _mapper;
        private readonly IStudentRepository _studentRepository;
        private readonly IProfessorRepository _professorRepository;

        public DashboardController(ICourseRepository courses, IMapper mapper,
            IStudentRepository studentRepo, IProfessorRepository profRepo)
        {
            _courses = courses;
            _mapper = mapper;
            _studentRepository = studentRepo;
            _professorRepository = profRepo;
        }

        [HttpGet("main")]
        public IActionResult MainPanel()
        {
            (string Name, string Surname) personInfo;
            switch (User.GetRole())
            {
                case DeanOfficeRoles.Student:
                    var student = _studentRepository.GetStudent(User.GetGuid());
                    personInfo = (student.FirstName, student.LastName);
                    break;
                case DeanOfficeRoles.Professor:
                    var professor = _professorRepository.GetProfessor(User.GetGuid());
                    personInfo = (professor.FirstName, professor.LastName);
                    break;
                default:
                    personInfo = ("Unknown", "Unknown");
                    break;
            }

            var model = new CourseDashboardViewModel()
            {
                UserRole = User.GetRole(),
                Name = personInfo.Name,
                Surname = personInfo.Surname
            };

            return View(model);
        }

        [HttpGet("schedule")]
        public IActionResult GetSchedule()
        {
            var courses = _courses.GetCoursesFor(User.GetRole(), User.GetGuid());
            var mappedCourses = _mapper.Map<IEnumerable<CourseDto>>(courses);
            var model = new CourseDashboardViewModel()
            {
                UserRole = User.GetRole(),
                Courses = mappedCourses
            };

            return View(model);
        }

        [HttpGet("courses")]
        public IActionResult GetAllCourses()
        {
            var courses = _courses.GetAllCourses();
            var mappedCourses = _mapper.Map<IEnumerable<CourseDto>>(courses);
            var model = new AllCoursesViewModel
            {
                Courses = mappedCourses
            };

            return View(model);
        }

        [HttpGet("course/{courseId:guid}/details")]
        public IActionResult CourseDetails(Guid courseId, [FromQuery]string returnUrl)
        {
            var course = _courses.GetCourse(courseId);
            var mappedCourse = _mapper.Map<CourseDtoWithAttendants>(course);

            var model = new CourseDetailsViewModel
            {
                Course = mappedCourse,
                IsPersonSignedUp = mappedCourse.IsPersonSignedForCourse(User.GetGuid()),
                IsStudent = User.IsStudent(),
                HasAdminRights = User.HasAdminRights(),
                ReturnUrl = returnUrl
            };

            return View(model);
        }
    }
}

DeanOffice/DeanOffice.Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0 shrink-to-fit=no" />
    <title>@ViewData["Title"] - Dean Office</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/fonts.css" />
    <link rel="stylesheet" href="~/css/hovers.css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto|Permanent+Marker" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #4E5C54">
        <a class="navbar-brand" href="#">
            <img src="~/images/nuclear_heart.bmp" />
            <b class="stylish-header font-very-big">Dean's office</b>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse roboto" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link nav-on-hover" asp-controller="Home" asp-action="Index"><b>Home</b></a>
                </li>
                <li>
                    <a class="nav-link nav-on-hover" asp-controller="Dashboard" asp-action="MainPanel"><b>Courses</b></a>
                </li>
                <li>
                    <a class="nav-link nav-on-hover" asp-controller="About" asp-action="Contact"><b>About</b></a>
                </li>
                @if (User.Identity.IsAuthenticated && User.HasAdminRights())
                {
                    <li>
                        <a class="nav-link nav-on-hover" asp-controller="Admin" asp-action="Index"><b>Administration</b></a>
                    </li>
                }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>
    <div class="container" style="padding-top:30px">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - DeanOffice</p>
        </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>