DeanOffice/DeanOffice.Application/Controllers/CourseController.cs
using AutoMapper;
using DeanOffice.Data.DatabaseEntities;
using DeanOffice.Models.DataTransferObjects.Course;
using DeanOffice.Models.DataTransferObjects.Professor;
using DeanOffice.Models.DataTransferObjects.Subject;
using DeanOffice.Models.ViewModels.Course;
using DeanOffice.Repository.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using DeanOffice.Models.ViewModels.Error;

namespace DeanOffice.Application.Controllers
{
    [Authorize(Policy = "DeanOfficer")]
    [Route("courses")]
    public class CourseController : Controller
    {
        private readonly IProfessorRepository _lecturerRepository;
        private readonly ICourseRepository _courseRepository;
        private readonly ISubjectRepository _subjectRepository;
        private readonly IMapper _mapper;

        public CourseController(ICourseRepository courseRepo, IMapper mapper,
            ISubjectRepository subjectRepo, IProfessorRepository professorRepo)
        {
            _lecturerRepository = professorRepo;
            _courseRepository = courseRepo;
            _subjectRepository = subjectRepo;
            _mapper = mapper;
        }

        [HttpGet("add")]
        public IActionResult Add()
        {
            var model = new CourseEditViewModel()
            {
                Course = new CourseDto(),
            };
            SetPropertiesOnCourseEditViewModel(model);

            ViewData["Title"] = "Add course";
            return View("AddEdit", model);
        }

        [HttpPost("add/{courseId:guid}")]
        [ValidateAntiForgeryToken]
        public IActionResult Add(Guid courseId, [FromQuery]string returnUrl, [FromBody]CourseEditViewModel model)
        {
            if (courseId != Guid.Empty)
            {
                var errorModel = new ErrorViewModel
                {
                    ErrorMessage = "Course already in database",
                    ReturnUrl = returnUrl
                };
                return View("Error", errorModel);
            }

            if (ModelState.IsValid)
            {
                var course = _mapper.Map<Course>(model.Course);
                _courseRepository.AddCourse(course);
                return RedirectToAction("GetAllCourses", "Dashboard");
            }

            SetPropertiesOnCourseEditViewModel(model);

            ViewData["Title"] = "Add course";
            return View("AddEdit", model);
        }

        [HttpGet("edit/{courseId:guid}")]
        public IActionResult Edit(Guid courseId, [FromQuery]string returnUrl)
        {
            var course = _courseRepository.GetCourse(courseId);
            if (course == null)
            {
                var errorModel = new ErrorViewModel
                {
                    ErrorMessage = "Course couldn't be found",
                    ReturnUrl = returnUrl
                };
                return View("Error", errorModel);
            }

            var mappedCourse = _mapper.Map<CourseDto>(course);

            var model = new CourseEditViewModel
            {
                Course = mappedCourse
            };

            SetPropertiesOnCourseEditViewModel(model);

            ViewData["Title"] = "Edit course";
            return View("AddEdit", model);
        }

        [HttpPost("edit/{courseId:guid}")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid courseId, CourseEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                SetPropertiesOnCourseEditViewModel(model);
                ViewData["Title"] = "Edit course";
                return View("AddEdit", model);
            }

            if (model.Course.CurrentStudentCount > model.Course.StudentCountLimit)
            {
                SetPropertiesOnCourseEditViewModel(model);
                ViewData["Title"] = "Edit course";
                ModelState.AddModelError("", "Cannot decrease student count further as students are signed in");
                return View("AddEdit", model);
            }

            var course = _mapper.Map<Course>(model.Course);
            _courseRepository.UpdateCourse(course);
            return RedirectToAction("GetAllCourses", "Dashboard");

        }

        private void SetPropertiesOnCourseEditViewModel(CourseEditViewModel model)
        {
            var subjects = _subjectRepository.GetSubjects();
            var lecturers = _lecturerRepository.GetProfessors();
            var types = _courseRepository.GetCourseTypes();

            var mappedSubjects = _mapper.Map<IEnumerable<SubjectBasicDto>>(subjects);
            var mappedLecturers = _mapper.Map<IEnumerable<ProfessorBasicDto>>(lecturers);
            var mappedTypes = _mapper.Map<IEnumerable<CourseTypeDto>>(types);

            model.SetLecturers(mappedLecturers);
            model.SetSubjects(mappedSubjects);
            model.SetTypes(mappedTypes);
        }
    }
}

DeanOffice/DeanOffice.Application/Controllers/CurriculumController.cs
using System;
using DeanOffice.Models.ViewModels.Error;
using DeanOffice.Repository.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DeanOffice.Application.Controllers
{
    [Route("curriculum")]
    [Authorize(Policy = "IsValidUser")]
    public class CurriculumController : Controller
    {
        private readonly ICurriculumRepository _curriculum;
        private readonly ICourseRepository _course;

        public CurriculumController(ICurriculumRepository curriculum, ICourseRepository courseRepo)
        {
            _curriculum = curriculum;
            _course = courseRepo;
        }

        [HttpPost("sigup/{courseId:guid}/{studentId:guid}")]
        public IActionResult SignUpForACourse(Guid courseId, Guid studentId, [FromQuery]string returnUrl)
        {
            var course = _course.GetCourse(courseId);
            if (course.Students.Count >= course.StudentCountLimit)
            {
                var errorModel = new ErrorViewModel
                {
                    ErrorMessage =
                        "Maximum number of students being signed up has been reached. You can't be signed up",
                    ReturnUrl = returnUrl
                };
                return View("Error", errorModel);
            }
            _curriculum.SignUpForLecture(studentId, courseId);

            return RedirectToAction("MainPanel", "Dashboard");
        }

        [HttpPost("sigout/{courseId:guid}/{studentId:guid}")]
        public IActionResult SignOutFromACourse(Guid courseId, Guid studentId)
        {
            _curriculum.SignOutFromLecture(studentId, courseId);

            return RedirectToAction("MainPanel", "Dashboard");
        }
    }
}

DeanOffice/DeanOffice.Application/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using AutoMapper;
using DeanOffice.Application.Utils;
using DeanOffice.Identity.Models;
using DeanOffice.Models.DataTransferObjects.Course;
using DeanOffice.Models.Utils;
using DeanOffice.Models.ViewModels.Dashboard;
using DeanOffice.Repository.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DeanOffice.Application.Controllers
{
    [Authorize(Policy = "IsValidUser")]
    [Route("dashboard")]
    public class DashboardController : Controller
    {
        private readonly ICourseRepository _courses;
        private readonly IMapper _mapper;
        private readonly IStudentRepository _studentRepository;
        private readonly IProfessorRepository _professorRepository;

        public DashboardController(ICourseRepository courses, IMapper mapper,
            IStudentRepository studentRepo, IProfessorRepository profRepo)
        {
            _courses = courses;
            _mapper = mapper;
            _studentRepository = studentRepo;
            _professorRepository = profRepo;
        }

        [HttpGet("main")]
        public IActionResult MainPanel()
        {
            (string Name, string Surname) personInfo;
            switch (User.GetRole())
            {
                case DeanOfficeRoles.Student:
                    var student = _studentRepository.GetStudent(User.GetGuid());
                    personInfo = (student.FirstName, student.LastName);
                    break;
                case DeanOfficeRoles.Professor:
                    var professor = _professorRepository.GetProfessor(User.GetGuid());
                    personInfo = (professor.FirstName, professor.LastName);
                    break;
                default:
                    personInfo = ("Unknown", "Unknown");
                    break;
            }

            var model = new CourseDashboardViewModel()
            {
                UserRole = User.GetRole(),
                Name = personInfo.Name,
                Surname = personInfo.Surname
            };

            return View(model);
        }

        [HttpGet("schedule")]
        public IActionResult GetSchedule()
        {
            var courses = _courses.GetCoursesFor(User.GetRole(), User.GetGuid());
            var mappedCourses = _mapper.Map<IEnumerable<CourseDto>>(courses);
            var model = new CourseDashboardViewModel()
            {
                UserRole = User.GetRole(),
                Courses = mappedCourses
            };

            return View(model);
        }

        [HttpGet("courses")]
        public IActionResult GetAllCourses()
        {
            var courses = _courses.GetAllCourses();
            var mappedCourses = _mapper.Map<IEnumerable<CourseDto>>(courses);
            var model = new AllCoursesViewModel
            {
                Courses = mappedCourses
            };

            return View(model);
        }

        [HttpGet("course/{courseId:guid}/details")]
        public IActionResult CourseDetails(Guid courseId, [FromQuery]string returnUrl)
        {
            var course = _courses.GetCourse(courseId);
            var mappedCourse = _mapper.Map<CourseDtoWithAttendants>(course);

            var model = new CourseDetailsViewModel
            {
                Course = mappedCourse,
                IsPersonSignedUp = mappedCourse.IsPersonSignedForCourse(User.GetGuid()),
                IsStudent = User.IsStudent(),
                HasAdminRights = User.HasAdminRights(),
                ReturnUrl = returnUrl
            };

            return View(model);
        }
    }
}

DeanOffice/DeanOffice.Application/Views/Dashboard/CourseDetails.cshtml
@model CourseDetailsViewModel
@{
    ViewData["Title"] = Model.Course.Name;
    ViewBag.CurriculumAction = Model.IsPersonSignedUp ? "SignOutFromACourse" : "SignUpForACourse";
    ViewBag.CurriculumActionText = Model.IsPersonSignedUp ? "SignOut" : "SignUp";
}
<h2 class="col-md-offset-1 stylish-header"><b>Course details - @Model.Course.Name </b></h2>
<div class="jumbotron roboto font-large">
    <div class="row">
        <div class="col">
            <div>
                <p>@Model.Course.Name</p>
                <p>@Model.Course.Subject.Name</p>
            </div>
            <div>
                <p>@Model.Course.Lecturer.FullName</p>
            </div>
            <div>
                <p>Duration: @Model.Course.StartupDate.ToShortDateString() to @Model.Course.FinishDate.ToShortDateString()</p>
            </div>
            <div>
                <p>Time : @Model.Course.StartHour - @Model.Course.EndHour (@(Model.Course.EndHour - Model.Course.StartHour))</p>
            </div>
            <div>
                <p>Currently signed in students: @Model.Course.CurrentStudentCount / @Model.Course.StudentCountLimit</p>
            </div>
        </div>
        <div class="col">
            <div>
                <a class="btn btn-primary" href="#" onclick="history.go(-1);return false;">Back</a>
            </div>
            @if (Model.HasAdminRights)
            {
                <a asp-controller="Course" asp-action="Edit"
                   asp-route-courseId="@Model.Course.CourseId"
                   asp-route-returnUrl="@Context.Request.Path"
                   class="btn btn-primary">
                    Edit
                </a>
            }
            @if (Model.IsStudent)
            {
                <form method="post" asp-antiforgery="true"
                      asp-controller="Curriculum"
                      asp-action="@ViewBag.CurriculumAction"
                      asp-route-courseId="@Model.Course.CourseId"
                      asp-route-studentId="@User.GetGuid()"
                      asp-route-returnUrl="@Context.Request.Path">
                    <input type="submit" class="btn btn-primary" value="@ViewBag.CurriculumActionText" />
                </form>
            }
            @if (!Model.IsStudent)
            {
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int i = 1;
                            foreach (var student in Model.Course.Attendants)
                            {
                                <tr>
                                    <td>@(i++.ToString())</td>
                                    <td>@student.FirstName @student.LastName</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            }
        </div>
    </div>
</div>

DeanOffice/DeanOffice.Application/Views/Dashboard/GetAllCourses.cshtml
@model AllCoursesViewModel
@{
    ViewData["Title"] = "All Courses";
}

<h2 class="col-md-offset-1 stylish-header"><b>All courses</b></h2>
<br />
<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Subject</th>
            <th scope="col">Lecturer</th>
            <th scope="col">Start date</th>
            <th scope="col">End date</th>
            <th scope="col">###</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var course in Model.Courses)
        {
            <tr>
                <td>@course.Name</td>
                <td>@course.Subject.Name</td>
                <td>@course.Lecturer.FirstName @course.Lecturer.LastName</td>
                <td>@course.StartupDate.ToShortDateString()</td>
                <td>@course.FinishDate.ToShortDateString()</td>
                <td><a asp-controller="Dashboard" asp-action="CourseDetails" 
                       asp-route-courseId="@course.CourseId" 
                       asp-route-returnUrl="@Context.Request.Path"
                       class="btn btn-primary">
                        Details
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

DeanOffice/DeanOffice.Application/Views/Dashboard/GetSchedule.cshtml
@model CourseDashboardViewModel

@{
    ViewBag.Title = "Schedule";
}

<h2 class="col-md-offset-1 stylish-header">
    <b>Schedule</b>
</h2>
<br />
<table class="table table-sm">
    <thead class="thead-light roboto">
        <tr>
            <th>Day</th>
            <th>Subject</th>
            <th>Name</th>
            <th>Type</th>
            <th>Starts</th>
            <th>Ends</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var dayGroup in Model.Courses.GroupBy(x => x.DayOfWeek).OrderBy(x => x.Key))
        {
            <tr class="roboto">
                <td><p class="stylish-header font-large">@dayGroup.Key</p></td>
                <td>@dayGroup?.First().Subject.Name</td>
                <td>@dayGroup?.First().Name</td>
                <td>@dayGroup?.First().Type.Name</td>
                <td>@dayGroup?.First().StartHour</td>
                <td>@dayGroup?.First().EndHour</td>
            </tr>
            foreach (var course in dayGroup.Skip(1).OrderBy(x => x.StartHour))
            {
                <tr class="roboto">
                    <td></td>
                    <td>@course.Subject.Name</td>
                    <td>@course.Name</td>
                    <td>@course.Type.Name</td>
                    <td>@course.StartHour</td>
                    <td>@course.EndHour</td>
                </tr>
            }
            <tr>
                <td colspan="50" class="green-background"></td>
            </tr>
        }
    </tbody>
</table>

DeanOffice/DeanOffice.Application/Views/Dashboard/MainPanel.cshtml
@model CourseDashboardViewModel

@{
    ViewData["Title"] = "Dashboard";
}
<h2 class="col-md-offset-1 stylish-header"><b>Dashboard</b></h2>
<div class="jumbotron roboto">
    <div class="row">
        <div class="col">
            <div>
                <p class="stylish-header font-large">Your information:</p>
            </div>
            <div>
                <p>Name : @Model.Name @Model.Surname</p>
                <p>CurrentRole: @Model.UserRole</p>
            </div>
        </div>
        <div class="col">
            <a asp-controller="Dashboard" asp-action="GetSchedule">Your schedule</a>
            <br />
            <a asp-controller="Dashboard" asp-action="GetAllCourses">Available courses</a>
        </div>
    </div>
</div>