DeanOffice/DeanOffice.Application/Controllers/SubjectController.cs
using System;
using DeanOffice.Data.DatabaseEntities;
using DeanOffice.Models.ViewModels.Subject;
using DeanOffice.Repository.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DeanOffice.Application.Controllers
{
    [Authorize(Policy = "DeanOfficer")]
    [Route("subjects")]
    public class SubjectController : Controller
    {
        private readonly ISubjectRepository _subjectRepository;

        public SubjectController(ISubjectRepository subjectRepository)
        {
            _subjectRepository = subjectRepository;
        }

        [HttpGet("")]
        public IActionResult GetAllSubjects()
        {
            var subjects = _subjectRepository.GetSubjects();

            return View(subjects);
        }

        [HttpGet("add")]
        public IActionResult AddSubject([FromQuery]string returnUrl)
        {
            var model = new SubjectAddEditViewModel()
            {
                ReturnUrl = returnUrl,
                Subject = new Subject()
            };

            return View("AddEditSubject", model);
        }

        [HttpGet("edit")]
        public IActionResult EditSubject([FromQuery]string returnUrl, [FromQuery] string subjectId)
        {
            var model = new SubjectAddEditViewModel()
            {
                ReturnUrl = returnUrl,
                Subject = _subjectRepository.GetSubject(Guid.Parse(subjectId))
            };

            return View("AddEditSubject", model);
        }

        [HttpPost("add")]
        public IActionResult AddSubject(SubjectAddEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("AddEditSubject", model);
            }

            _subjectRepository.AddSubject(model.Subject);
            return Redirect(model.ReturnUrl);
        }

        [HttpPost("edit")]
        public IActionResult EditSubject(SubjectAddEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("AddEditSubject", model);
            }

            _subjectRepository.UpdateSubject(model.Subject);
            return Redirect(model.ReturnUrl);
        }
    }
}

DeanOffice/DeanOffice.Application/Views/Subject/AddEditSubject.cshtml
@model SubjectAddEditViewModel

@{
    ViewData["Title"] = "Add subject";
}

<h2>@ViewData["Title"]</h2>
<form method="post" class="form-horizontal roboto bold"
      asp-antiforgery="true"
      asp-controller="Subject"
      asp-action="@(Model.Subject.SubjectId == Guid.Empty ? "AddSubject" : "EditSubject")">
    <div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label class="control-label" asp-for="Subject.Name"></label>
                    <div>
                        <input class="form-control" asp-for="Subject.Name" />
                        <input class="form-control" type="hidden" asp-for="Subject.SubjectId" />
                        <input class="form-control" type="hidden" asp-for="ReturnUrl"/>
                        <span asp-validation-for="Subject.Name" class="font-error"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <input class="btn btn-success btn-lg col-md-offset-5" type="submit" value="@(Model.Subject.SubjectId == Guid.Empty ? "Add" : "Edit")" />
    </div>
    <br />
    <div asp-validation-summary="ModelOnly" class="font-error"></div>
</form>

DeanOffice/DeanOffice.Application/Views/Subject/GetAllSubjects.cshtml
@model IEnumerable<DeanOffice.Data.DatabaseEntities.Subject>

@{
    ViewData["Title"] = "All subjects";
}

<h2 class="col-md-offset-1 stylish-header"><b>All subjects</b></h2>
<br />
<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">###</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var subject in Model)
        {
            {
                ViewBag.ActionToExecute = subject.SubjectId == Guid.Empty ? "AddSubject" : "EditSubject";
            }
            <tr>
                <td>@subject.Name</td>
                <td>
                    <a asp-controller="Subject" asp-action="@ViewBag.ActionToExecute"
                       asp-route-subjectId="@subject.SubjectId"
                       asp-route-returnUrl="@Context.Request.Path"
                       class="btn btn-primary">
                        Edit
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>